### ISSUE TITLE
Amazing loops for mazes with the vertical dimension = 2

### ISSUE THREAD

**Issue by maurymarkowitz** [maurymarkowitz/RetroBASIC#4]
Works fine for 3x3, 2x3, but 3x2 or 2x2 will go into an infinite loop. This does work in the PET emulator.

**Comment by maurymarkowitz** [comment]
Fixed in 1.8.3. Dangling pointer when setting up small arrays at runtime.

**Comment by maurymarkowitz** [comment]
Fixed in 1.8.3. Dangling pointer when setting up small arrays at runtime.

**Comment by maurymarkowitz** [comment]
The problem with small mazes is fixed, but it continues to periodically go into a loop on any sized maze. The pattern is not entirely clear, it loops between lines 740 and 1000 when it should exit quickly. It may be an issue with arrays (most likely) or perhaps the comparison between the value in the array and the calculated value, thus in the = operator.

**Comment by scruss** [comment]
While I can't repeat this with any Linux/gcc build, I *can* using XCode 14.2 / MacOS 12.7.1. As it took me a couple of hours to understand how to make things build in that IDE, I'm not sure I can be of much extra help

Your `amazing.bas` is somewhat different from the one in the CodingHorror repo But that's not the source of the problem

**Comment by maurymarkowitz** [comment]
Interesting!

Now I’m thinking this may be due to either the random system. Ok, I’ll insert lots of PRINTs and see what happens. This may or may not be interesting in the end...

**Comment by maurymarkowitz** [comment]
Fixed in v.1.8.6. malloc'ing instead of calloc'ing in the array initialization code.
