### ISSUE TITLE
Request: Gosub to Labels not line Numbers

### ISSUE THREAD

**Issue by snakebyte69** [maurymarkowitz/RetroBASIC#5]
Can RetroBasic Gosub to a label, if not can you add this feature please

**Comment by maurymarkowitz** [comment]
This is already possible, in a way - branches can have any expression, not just a number, so you could say "GOSUB B+10" for instance. So if you want to GOSUB to line 500, you could LET B=500:GOSUB B.

I am thinking about adding an actual LABEL statement as well, I'll let you know if I get this working.

**Comment by maurymarkowitz** [comment]
Added a LABEL statement that takes a valid variable name as a marker. Eg:

100 GOSUB TE
...
5000 LABEL TE

As branches always go to the start of a line, placing a LABEL in the middle of a line will still branch to the start. To avoid confusion, LABELs should generally be the first statement on a line.
